// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0--rc2
// source: api/proto/kore.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandOutput_OutputType int32

const (
	CommandOutput_STDOUT CommandOutput_OutputType = 0
	CommandOutput_STDERR CommandOutput_OutputType = 1
	CommandOutput_EXIT   CommandOutput_OutputType = 2
)

// Enum value maps for CommandOutput_OutputType.
var (
	CommandOutput_OutputType_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
		2: "EXIT",
	}
	CommandOutput_OutputType_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
		"EXIT":   2,
	}
)

func (x CommandOutput_OutputType) Enum() *CommandOutput_OutputType {
	p := new(CommandOutput_OutputType)
	*p = x
	return p
}

func (x CommandOutput_OutputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandOutput_OutputType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_kore_proto_enumTypes[0].Descriptor()
}

func (CommandOutput_OutputType) Type() protoreflect.EnumType {
	return &file_api_proto_kore_proto_enumTypes[0]
}

func (x CommandOutput_OutputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandOutput_OutputType.Descriptor instead.
func (CommandOutput_OutputType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{3, 0}
}

type MessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // "user", "assistant", "system"
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	mi := &file_api_proto_kore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{0}
}

func (x *MessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MessageRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Done          bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_api_proto_kore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{1}
}

func (x *MessageResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MessageResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *MessageResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Background    bool                   `protobuf:"varint,6,opt,name=background,proto3" json:"background,omitempty"` // 是否后台运行
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_api_proto_kore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{2}
}

func (x *CommandRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CommandRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *CommandRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CommandRequest) GetBackground() bool {
	if x != nil {
		return x.Background
	}
	return false
}

type CommandOutput struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Type          CommandOutput_OutputType `protobuf:"varint,1,opt,name=type,proto3,enum=kore.CommandOutput_OutputType" json:"type,omitempty"`
	Data          []byte                   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ExitCode      int32                    `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Pid           int32                    `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"` // 进程 ID（后台进程时使用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandOutput) Reset() {
	*x = CommandOutput{}
	mi := &file_api_proto_kore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOutput) ProtoMessage() {}

func (x *CommandOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOutput.ProtoReflect.Descriptor instead.
func (*CommandOutput) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{3}
}

func (x *CommandOutput) GetType() CommandOutput_OutputType {
	if x != nil {
		return x.Type
	}
	return CommandOutput_STDOUT
}

func (x *CommandOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CommandOutput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandOutput) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type LSPCompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FileUri       string                 `protobuf:"bytes,2,opt,name=file_uri,json=fileUri,proto3" json:"file_uri,omitempty"`
	Line          int32                  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Character     int32                  `protobuf:"varint,4,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LSPCompleteRequest) Reset() {
	*x = LSPCompleteRequest{}
	mi := &file_api_proto_kore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LSPCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSPCompleteRequest) ProtoMessage() {}

func (x *LSPCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSPCompleteRequest.ProtoReflect.Descriptor instead.
func (*LSPCompleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{4}
}

func (x *LSPCompleteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LSPCompleteRequest) GetFileUri() string {
	if x != nil {
		return x.FileUri
	}
	return ""
}

func (x *LSPCompleteRequest) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *LSPCompleteRequest) GetCharacter() int32 {
	if x != nil {
		return x.Character
	}
	return 0
}

type LSPCompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CompletionItem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	IsIncomplete  bool                   `protobuf:"varint,2,opt,name=is_incomplete,json=isIncomplete,proto3" json:"is_incomplete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LSPCompleteResponse) Reset() {
	*x = LSPCompleteResponse{}
	mi := &file_api_proto_kore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LSPCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSPCompleteResponse) ProtoMessage() {}

func (x *LSPCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSPCompleteResponse.ProtoReflect.Descriptor instead.
func (*LSPCompleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{5}
}

func (x *LSPCompleteResponse) GetItems() []*CompletionItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *LSPCompleteResponse) GetIsIncomplete() bool {
	if x != nil {
		return x.IsIncomplete
	}
	return false
}

type CompletionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // "Function", "Variable", "Class", etc.
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Documentation string                 `protobuf:"bytes,4,opt,name=documentation,proto3" json:"documentation,omitempty"`
	InsertText    string                 `protobuf:"bytes,5,opt,name=insert_text,json=insertText,proto3" json:"insert_text,omitempty"`
	SortText      string                 `protobuf:"bytes,6,opt,name=sort_text,json=sortText,proto3" json:"sort_text,omitempty"`
	Data          map[string]string      `protobuf:"bytes,7,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionItem) Reset() {
	*x = CompletionItem{}
	mi := &file_api_proto_kore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionItem) ProtoMessage() {}

func (x *CompletionItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionItem.ProtoReflect.Descriptor instead.
func (*CompletionItem) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{6}
}

func (x *CompletionItem) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CompletionItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CompletionItem) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *CompletionItem) GetDocumentation() string {
	if x != nil {
		return x.Documentation
	}
	return ""
}

func (x *CompletionItem) GetInsertText() string {
	if x != nil {
		return x.InsertText
	}
	return ""
}

func (x *CompletionItem) GetSortText() string {
	if x != nil {
		return x.SortText
	}
	return ""
}

func (x *CompletionItem) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type LSPDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FileUri       string                 `protobuf:"bytes,2,opt,name=file_uri,json=fileUri,proto3" json:"file_uri,omitempty"`
	Line          int32                  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Character     int32                  `protobuf:"varint,4,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LSPDefinitionRequest) Reset() {
	*x = LSPDefinitionRequest{}
	mi := &file_api_proto_kore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LSPDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSPDefinitionRequest) ProtoMessage() {}

func (x *LSPDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSPDefinitionRequest.ProtoReflect.Descriptor instead.
func (*LSPDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{7}
}

func (x *LSPDefinitionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LSPDefinitionRequest) GetFileUri() string {
	if x != nil {
		return x.FileUri
	}
	return ""
}

func (x *LSPDefinitionRequest) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *LSPDefinitionRequest) GetCharacter() int32 {
	if x != nil {
		return x.Character
	}
	return 0
}

type LSPDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*Location            `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LSPDefinitionResponse) Reset() {
	*x = LSPDefinitionResponse{}
	mi := &file_api_proto_kore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LSPDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSPDefinitionResponse) ProtoMessage() {}

func (x *LSPDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSPDefinitionResponse.ProtoReflect.Descriptor instead.
func (*LSPDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{8}
}

func (x *LSPDefinitionResponse) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Range         *Range                 `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_api_proto_kore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{9}
}

func (x *Location) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Location) GetRange() *Range {
	if x != nil {
		return x.Range
	}
	return nil
}

type Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *Position              `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *Position              `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Range) Reset() {
	*x = Range{}
	mi := &file_api_proto_kore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{10}
}

func (x *Range) GetStart() *Position {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Range) GetEnd() *Position {
	if x != nil {
		return x.End
	}
	return nil
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          int32                  `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`           // 0-based
	Character     int32                  `protobuf:"varint,2,opt,name=character,proto3" json:"character,omitempty"` // 0-based
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_api_proto_kore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{11}
}

func (x *Position) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Position) GetCharacter() int32 {
	if x != nil {
		return x.Character
	}
	return 0
}

type LSPHoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FileUri       string                 `protobuf:"bytes,2,opt,name=file_uri,json=fileUri,proto3" json:"file_uri,omitempty"`
	Line          int32                  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Character     int32                  `protobuf:"varint,4,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LSPHoverRequest) Reset() {
	*x = LSPHoverRequest{}
	mi := &file_api_proto_kore_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LSPHoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSPHoverRequest) ProtoMessage() {}

func (x *LSPHoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSPHoverRequest.ProtoReflect.Descriptor instead.
func (*LSPHoverRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{12}
}

func (x *LSPHoverRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LSPHoverRequest) GetFileUri() string {
	if x != nil {
		return x.FileUri
	}
	return ""
}

func (x *LSPHoverRequest) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *LSPHoverRequest) GetCharacter() int32 {
	if x != nil {
		return x.Character
	}
	return 0
}

type LSPHoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      string                 `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
	Range         *Range                 `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LSPHoverResponse) Reset() {
	*x = LSPHoverResponse{}
	mi := &file_api_proto_kore_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LSPHoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSPHoverResponse) ProtoMessage() {}

func (x *LSPHoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSPHoverResponse.ProtoReflect.Descriptor instead.
func (*LSPHoverResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{13}
}

func (x *LSPHoverResponse) GetContents() string {
	if x != nil {
		return x.Contents
	}
	return ""
}

func (x *LSPHoverResponse) GetRange() *Range {
	if x != nil {
		return x.Range
	}
	return nil
}

type LSPReferencesRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FileUri            string                 `protobuf:"bytes,2,opt,name=file_uri,json=fileUri,proto3" json:"file_uri,omitempty"`
	Line               int32                  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Character          int32                  `protobuf:"varint,4,opt,name=character,proto3" json:"character,omitempty"`
	IncludeDeclaration bool                   `protobuf:"varint,5,opt,name=include_declaration,json=includeDeclaration,proto3" json:"include_declaration,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LSPReferencesRequest) Reset() {
	*x = LSPReferencesRequest{}
	mi := &file_api_proto_kore_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LSPReferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSPReferencesRequest) ProtoMessage() {}

func (x *LSPReferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSPReferencesRequest.ProtoReflect.Descriptor instead.
func (*LSPReferencesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{14}
}

func (x *LSPReferencesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LSPReferencesRequest) GetFileUri() string {
	if x != nil {
		return x.FileUri
	}
	return ""
}

func (x *LSPReferencesRequest) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *LSPReferencesRequest) GetCharacter() int32 {
	if x != nil {
		return x.Character
	}
	return 0
}

func (x *LSPReferencesRequest) GetIncludeDeclaration() bool {
	if x != nil {
		return x.IncludeDeclaration
	}
	return false
}

type LSPReferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*Location            `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LSPReferencesResponse) Reset() {
	*x = LSPReferencesResponse{}
	mi := &file_api_proto_kore_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LSPReferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSPReferencesResponse) ProtoMessage() {}

func (x *LSPReferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSPReferencesResponse.ProtoReflect.Descriptor instead.
func (*LSPReferencesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{15}
}

func (x *LSPReferencesResponse) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

type LSPRenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FileUri       string                 `protobuf:"bytes,2,opt,name=file_uri,json=fileUri,proto3" json:"file_uri,omitempty"`
	Line          int32                  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Character     int32                  `protobuf:"varint,4,opt,name=character,proto3" json:"character,omitempty"`
	NewName       string                 `protobuf:"bytes,5,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LSPRenameRequest) Reset() {
	*x = LSPRenameRequest{}
	mi := &file_api_proto_kore_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LSPRenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSPRenameRequest) ProtoMessage() {}

func (x *LSPRenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSPRenameRequest.ProtoReflect.Descriptor instead.
func (*LSPRenameRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{16}
}

func (x *LSPRenameRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LSPRenameRequest) GetFileUri() string {
	if x != nil {
		return x.FileUri
	}
	return ""
}

func (x *LSPRenameRequest) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *LSPRenameRequest) GetCharacter() int32 {
	if x != nil {
		return x.Character
	}
	return 0
}

func (x *LSPRenameRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type LSPRenameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edit          *WorkspaceEdit         `protobuf:"bytes,1,opt,name=edit,proto3" json:"edit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LSPRenameResponse) Reset() {
	*x = LSPRenameResponse{}
	mi := &file_api_proto_kore_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LSPRenameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSPRenameResponse) ProtoMessage() {}

func (x *LSPRenameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSPRenameResponse.ProtoReflect.Descriptor instead.
func (*LSPRenameResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{17}
}

func (x *LSPRenameResponse) GetEdit() *WorkspaceEdit {
	if x != nil {
		return x.Edit
	}
	return nil
}

type WorkspaceEdit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*DocumentChange      `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceEdit) Reset() {
	*x = WorkspaceEdit{}
	mi := &file_api_proto_kore_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceEdit) ProtoMessage() {}

func (x *WorkspaceEdit) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceEdit.ProtoReflect.Descriptor instead.
func (*WorkspaceEdit) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{18}
}

func (x *WorkspaceEdit) GetChanges() []*DocumentChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

type DocumentChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Edits         []*TextEdit            `protobuf:"bytes,2,rep,name=edits,proto3" json:"edits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentChange) Reset() {
	*x = DocumentChange{}
	mi := &file_api_proto_kore_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentChange) ProtoMessage() {}

func (x *DocumentChange) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentChange.ProtoReflect.Descriptor instead.
func (*DocumentChange) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{19}
}

func (x *DocumentChange) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *DocumentChange) GetEdits() []*TextEdit {
	if x != nil {
		return x.Edits
	}
	return nil
}

type TextEdit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Range         *Range                 `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	NewText       string                 `protobuf:"bytes,2,opt,name=new_text,json=newText,proto3" json:"new_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextEdit) Reset() {
	*x = TextEdit{}
	mi := &file_api_proto_kore_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextEdit) ProtoMessage() {}

func (x *TextEdit) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextEdit.ProtoReflect.Descriptor instead.
func (*TextEdit) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{20}
}

func (x *TextEdit) GetRange() *Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *TextEdit) GetNewText() string {
	if x != nil {
		return x.NewText
	}
	return ""
}

type LSPDiagnosticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FileUri       string                 `protobuf:"bytes,2,opt,name=file_uri,json=fileUri,proto3" json:"file_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LSPDiagnosticsRequest) Reset() {
	*x = LSPDiagnosticsRequest{}
	mi := &file_api_proto_kore_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LSPDiagnosticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSPDiagnosticsRequest) ProtoMessage() {}

func (x *LSPDiagnosticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSPDiagnosticsRequest.ProtoReflect.Descriptor instead.
func (*LSPDiagnosticsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{21}
}

func (x *LSPDiagnosticsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LSPDiagnosticsRequest) GetFileUri() string {
	if x != nil {
		return x.FileUri
	}
	return ""
}

type LSPDiagnosticEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diagnostic    *Diagnostic            `protobuf:"bytes,1,opt,name=diagnostic,proto3" json:"diagnostic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LSPDiagnosticEvent) Reset() {
	*x = LSPDiagnosticEvent{}
	mi := &file_api_proto_kore_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LSPDiagnosticEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSPDiagnosticEvent) ProtoMessage() {}

func (x *LSPDiagnosticEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSPDiagnosticEvent.ProtoReflect.Descriptor instead.
func (*LSPDiagnosticEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{22}
}

func (x *LSPDiagnosticEvent) GetDiagnostic() *Diagnostic {
	if x != nil {
		return x.Diagnostic
	}
	return nil
}

type Diagnostic struct {
	state              protoimpl.MessageState          `protogen:"open.v1"`
	Range              *Range                          `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	Severity           string                          `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"` // "Error", "Warning", "Info", "Hint"
	Source             string                          `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Message            string                          `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	RelatedInformation []*DiagnosticRelatedInformation `protobuf:"bytes,5,rep,name=related_information,json=relatedInformation,proto3" json:"related_information,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_api_proto_kore_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{23}
}

func (x *Diagnostic) GetRange() *Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Diagnostic) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Diagnostic) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Diagnostic) GetRelatedInformation() []*DiagnosticRelatedInformation {
	if x != nil {
		return x.RelatedInformation
	}
	return nil
}

type DiagnosticRelatedInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosticRelatedInformation) Reset() {
	*x = DiagnosticRelatedInformation{}
	mi := &file_api_proto_kore_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticRelatedInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticRelatedInformation) ProtoMessage() {}

func (x *DiagnosticRelatedInformation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticRelatedInformation.ProtoReflect.Descriptor instead.
func (*DiagnosticRelatedInformation) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{24}
}

func (x *DiagnosticRelatedInformation) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *DiagnosticRelatedInformation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AgentType     string                 `protobuf:"bytes,2,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"` // "build", "plan", "general"
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_api_proto_kore_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{25}
}

func (x *CreateSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSessionRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *CreateSessionRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_api_proto_kore_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{26}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_api_proto_kore_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{27}
}

func (x *ListSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSessionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_api_proto_kore_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{28}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_api_proto_kore_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{29}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_api_proto_kore_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{30}
}

func (x *CloseSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AgentType     string                 `protobuf:"bytes,3,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "idle", "running", "paused", "closed"
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastActiveAt  int64                  `protobuf:"varint,6,opt,name=last_active_at,json=lastActiveAt,proto3" json:"last_active_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_api_proto_kore_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{31}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *Session) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Session) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Session) GetLastActiveAt() int64 {
	if x != nil {
		return x.LastActiveAt
	}
	return 0
}

func (x *Session) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateVirtualDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"` // "file:///virtual/main.go"
	LanguageId    string                 `protobuf:"bytes,3,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVirtualDocRequest) Reset() {
	*x = CreateVirtualDocRequest{}
	mi := &file_api_proto_kore_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVirtualDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVirtualDocRequest) ProtoMessage() {}

func (x *CreateVirtualDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVirtualDocRequest.ProtoReflect.Descriptor instead.
func (*CreateVirtualDocRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{32}
}

func (x *CreateVirtualDocRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateVirtualDocRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *CreateVirtualDocRequest) GetLanguageId() string {
	if x != nil {
		return x.LanguageId
	}
	return ""
}

func (x *CreateVirtualDocRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateVirtualDocResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVirtualDocResponse) Reset() {
	*x = CreateVirtualDocResponse{}
	mi := &file_api_proto_kore_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVirtualDocResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVirtualDocResponse) ProtoMessage() {}

func (x *CreateVirtualDocResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVirtualDocResponse.ProtoReflect.Descriptor instead.
func (*CreateVirtualDocResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{33}
}

func (x *CreateVirtualDocResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateVirtualDocResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type UpdateVirtualDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVirtualDocRequest) Reset() {
	*x = UpdateVirtualDocRequest{}
	mi := &file_api_proto_kore_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVirtualDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVirtualDocRequest) ProtoMessage() {}

func (x *UpdateVirtualDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVirtualDocRequest.ProtoReflect.Descriptor instead.
func (*UpdateVirtualDocRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{34}
}

func (x *UpdateVirtualDocRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpdateVirtualDocRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *UpdateVirtualDocRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UpdateVirtualDocRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateVirtualDocResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVirtualDocResponse) Reset() {
	*x = UpdateVirtualDocResponse{}
	mi := &file_api_proto_kore_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVirtualDocResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVirtualDocResponse) ProtoMessage() {}

func (x *UpdateVirtualDocResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVirtualDocResponse.ProtoReflect.Descriptor instead.
func (*UpdateVirtualDocResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{35}
}

func (x *UpdateVirtualDocResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CloseVirtualDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseVirtualDocRequest) Reset() {
	*x = CloseVirtualDocRequest{}
	mi := &file_api_proto_kore_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseVirtualDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseVirtualDocRequest) ProtoMessage() {}

func (x *CloseVirtualDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseVirtualDocRequest.ProtoReflect.Descriptor instead.
func (*CloseVirtualDocRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{36}
}

func (x *CloseVirtualDocRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CloseVirtualDocRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type CloseVirtualDocResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseVirtualDocResponse) Reset() {
	*x = CloseVirtualDocResponse{}
	mi := &file_api_proto_kore_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseVirtualDocResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseVirtualDocResponse) ProtoMessage() {}

func (x *CloseVirtualDocResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseVirtualDocResponse.ProtoReflect.Descriptor instead.
func (*CloseVirtualDocResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{37}
}

func (x *CloseVirtualDocResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`    // 空字符串表示订阅所有会话
	EventTypes    []string               `protobuf:"bytes,2,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"` // 空列表表示订阅所有类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_proto_kore_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{38}
}

func (x *SubscribeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubscribeRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "llm_token", "tool_output", "status", etc.
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // JSON 编码的事件数据
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_proto_kore_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kore_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_proto_kore_proto_rawDescGZIP(), []int{39}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_proto_kore_proto protoreflect.FileDescriptor

const file_api_proto_kore_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/kore.proto\x12\x04kore\"\xda\x01\n" +
	"\x0eMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12>\n" +
	"\bmetadata\x18\x04 \x03(\v2\".kore.MessageRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xef\x01\n" +
	"\x0fMessageResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\x12?\n" +
	"\bmetadata\x18\x05 \x03(\v2#.kore.MessageResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x02\n" +
	"\x0eCommandRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12/\n" +
	"\x03env\x18\x05 \x03(\v2\x1d.kore.CommandRequest.EnvEntryR\x03env\x12\x1e\n" +
	"\n" +
	"background\x18\x06 \x01(\bR\n" +
	"background\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x01\n" +
	"\rCommandOutput\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.kore.CommandOutput.OutputTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x05R\x03pid\".\n" +
	"\n" +
	"OutputType\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\x12\b\n" +
	"\x04EXIT\x10\x02\"\x80\x01\n" +
	"\x12LSPCompleteRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bfile_uri\x18\x02 \x01(\tR\afileUri\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x1c\n" +
	"\tcharacter\x18\x04 \x01(\x05R\tcharacter\"f\n" +
	"\x13LSPCompleteResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.kore.CompletionItemR\x05items\x12#\n" +
	"\ris_incomplete\x18\x02 \x01(\bR\fisIncomplete\"\xa3\x02\n" +
	"\x0eCompletionItem\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12$\n" +
	"\rdocumentation\x18\x04 \x01(\tR\rdocumentation\x12\x1f\n" +
	"\vinsert_text\x18\x05 \x01(\tR\n" +
	"insertText\x12\x1b\n" +
	"\tsort_text\x18\x06 \x01(\tR\bsortText\x122\n" +
	"\x04data\x18\a \x03(\v2\x1e.kore.CompletionItem.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\x14LSPDefinitionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bfile_uri\x18\x02 \x01(\tR\afileUri\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x1c\n" +
	"\tcharacter\x18\x04 \x01(\x05R\tcharacter\"E\n" +
	"\x15LSPDefinitionResponse\x12,\n" +
	"\tlocations\x18\x01 \x03(\v2\x0e.kore.LocationR\tlocations\"?\n" +
	"\bLocation\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12!\n" +
	"\x05range\x18\x02 \x01(\v2\v.kore.RangeR\x05range\"O\n" +
	"\x05Range\x12$\n" +
	"\x05start\x18\x01 \x01(\v2\x0e.kore.PositionR\x05start\x12 \n" +
	"\x03end\x18\x02 \x01(\v2\x0e.kore.PositionR\x03end\"<\n" +
	"\bPosition\x12\x12\n" +
	"\x04line\x18\x01 \x01(\x05R\x04line\x12\x1c\n" +
	"\tcharacter\x18\x02 \x01(\x05R\tcharacter\"}\n" +
	"\x0fLSPHoverRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bfile_uri\x18\x02 \x01(\tR\afileUri\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x1c\n" +
	"\tcharacter\x18\x04 \x01(\x05R\tcharacter\"Q\n" +
	"\x10LSPHoverResponse\x12\x1a\n" +
	"\bcontents\x18\x01 \x01(\tR\bcontents\x12!\n" +
	"\x05range\x18\x02 \x01(\v2\v.kore.RangeR\x05range\"\xb3\x01\n" +
	"\x14LSPReferencesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bfile_uri\x18\x02 \x01(\tR\afileUri\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x1c\n" +
	"\tcharacter\x18\x04 \x01(\x05R\tcharacter\x12/\n" +
	"\x13include_declaration\x18\x05 \x01(\bR\x12includeDeclaration\"E\n" +
	"\x15LSPReferencesResponse\x12,\n" +
	"\tlocations\x18\x01 \x03(\v2\x0e.kore.LocationR\tlocations\"\x99\x01\n" +
	"\x10LSPRenameRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bfile_uri\x18\x02 \x01(\tR\afileUri\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x1c\n" +
	"\tcharacter\x18\x04 \x01(\x05R\tcharacter\x12\x19\n" +
	"\bnew_name\x18\x05 \x01(\tR\anewName\"<\n" +
	"\x11LSPRenameResponse\x12'\n" +
	"\x04edit\x18\x01 \x01(\v2\x13.kore.WorkspaceEditR\x04edit\"?\n" +
	"\rWorkspaceEdit\x12.\n" +
	"\achanges\x18\x01 \x03(\v2\x14.kore.DocumentChangeR\achanges\"H\n" +
	"\x0eDocumentChange\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12$\n" +
	"\x05edits\x18\x02 \x03(\v2\x0e.kore.TextEditR\x05edits\"H\n" +
	"\bTextEdit\x12!\n" +
	"\x05range\x18\x01 \x01(\v2\v.kore.RangeR\x05range\x12\x19\n" +
	"\bnew_text\x18\x02 \x01(\tR\anewText\"Q\n" +
	"\x15LSPDiagnosticsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bfile_uri\x18\x02 \x01(\tR\afileUri\"F\n" +
	"\x12LSPDiagnosticEvent\x120\n" +
	"\n" +
	"diagnostic\x18\x01 \x01(\v2\x10.kore.DiagnosticR\n" +
	"diagnostic\"\xd2\x01\n" +
	"\n" +
	"Diagnostic\x12!\n" +
	"\x05range\x18\x01 \x01(\v2\v.kore.RangeR\x05range\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12S\n" +
	"\x13related_information\x18\x05 \x03(\v2\".kore.DiagnosticRelatedInformationR\x12relatedInformation\"d\n" +
	"\x1cDiagnosticRelatedInformation\x12*\n" +
	"\blocation\x18\x01 \x01(\v2\x0e.kore.LocationR\blocation\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc4\x01\n" +
	"\x14CreateSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\tR\tagentType\x12>\n" +
	"\x06config\x18\x03 \x03(\v2&.kore.CreateSessionRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"C\n" +
	"\x13ListSessionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"W\n" +
	"\x14ListSessionsResponse\x12)\n" +
	"\bsessions\x18\x01 \x03(\v2\r.kore.SessionR\bsessions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"0\n" +
	"\x14CloseSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9f\x02\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x03 \x01(\tR\tagentType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12$\n" +
	"\x0elast_active_at\x18\x06 \x01(\x03R\flastActiveAt\x127\n" +
	"\bmetadata\x18\a \x03(\v2\x1b.kore.Session.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x01\n" +
	"\x17CreateVirtualDocRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12\x1f\n" +
	"\vlanguage_id\x18\x03 \x01(\tR\n" +
	"languageId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"N\n" +
	"\x18CreateVirtualDocResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"~\n" +
	"\x17UpdateVirtualDocRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"4\n" +
	"\x18UpdateVirtualDocResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"I\n" +
	"\x16CloseVirtualDocRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\"3\n" +
	"\x17CloseVirtualDocResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"R\n" +
	"\x10SubscribeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vevent_types\x18\x02 \x03(\tR\n" +
	"eventTypes\"l\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp2\xe0\b\n" +
	"\x04Kore\x12:\n" +
	"\rCreateSession\x12\x1a.kore.CreateSessionRequest\x1a\r.kore.Session\x124\n" +
	"\n" +
	"GetSession\x12\x17.kore.GetSessionRequest\x1a\r.kore.Session\x12E\n" +
	"\fListSessions\x12\x19.kore.ListSessionsRequest\x1a\x1a.kore.ListSessionsResponse\x12E\n" +
	"\fCloseSession\x12\x19.kore.CloseSessionRequest\x1a\x1a.kore.CloseSessionResponse\x12>\n" +
	"\vSendMessage\x12\x14.kore.MessageRequest\x1a\x15.kore.MessageResponse(\x010\x01\x12=\n" +
	"\x0eExecuteCommand\x12\x14.kore.CommandRequest\x1a\x13.kore.CommandOutput0\x01\x12B\n" +
	"\vLSPComplete\x12\x18.kore.LSPCompleteRequest\x1a\x19.kore.LSPCompleteResponse\x12H\n" +
	"\rLSPDefinition\x12\x1a.kore.LSPDefinitionRequest\x1a\x1b.kore.LSPDefinitionResponse\x129\n" +
	"\bLSPHover\x12\x15.kore.LSPHoverRequest\x1a\x16.kore.LSPHoverResponse\x12H\n" +
	"\rLSPReferences\x12\x1a.kore.LSPReferencesRequest\x1a\x1b.kore.LSPReferencesResponse\x12<\n" +
	"\tLSPRename\x12\x16.kore.LSPRenameRequest\x1a\x17.kore.LSPRenameResponse\x12I\n" +
	"\x0eLSPDiagnostics\x12\x1b.kore.LSPDiagnosticsRequest\x1a\x18.kore.LSPDiagnosticEvent0\x01\x128\n" +
	"\x0fSubscribeEvents\x12\x16.kore.SubscribeRequest\x1a\v.kore.Event0\x01\x12V\n" +
	"\x15CreateVirtualDocument\x12\x1d.kore.CreateVirtualDocRequest\x1a\x1e.kore.CreateVirtualDocResponse\x12V\n" +
	"\x15UpdateVirtualDocument\x12\x1d.kore.UpdateVirtualDocRequest\x1a\x1e.kore.UpdateVirtualDocResponse\x12S\n" +
	"\x14CloseVirtualDocument\x12\x1c.kore.CloseVirtualDocRequest\x1a\x1d.kore.CloseVirtualDocResponseB%Z#github.com/yukin/kore/api/proto;rpcb\x06proto3"

var (
	file_api_proto_kore_proto_rawDescOnce sync.Once
	file_api_proto_kore_proto_rawDescData []byte
)

func file_api_proto_kore_proto_rawDescGZIP() []byte {
	file_api_proto_kore_proto_rawDescOnce.Do(func() {
		file_api_proto_kore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_kore_proto_rawDesc), len(file_api_proto_kore_proto_rawDesc)))
	})
	return file_api_proto_kore_proto_rawDescData
}

var file_api_proto_kore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_kore_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_api_proto_kore_proto_goTypes = []any{
	(CommandOutput_OutputType)(0),        // 0: kore.CommandOutput.OutputType
	(*MessageRequest)(nil),               // 1: kore.MessageRequest
	(*MessageResponse)(nil),              // 2: kore.MessageResponse
	(*CommandRequest)(nil),               // 3: kore.CommandRequest
	(*CommandOutput)(nil),                // 4: kore.CommandOutput
	(*LSPCompleteRequest)(nil),           // 5: kore.LSPCompleteRequest
	(*LSPCompleteResponse)(nil),          // 6: kore.LSPCompleteResponse
	(*CompletionItem)(nil),               // 7: kore.CompletionItem
	(*LSPDefinitionRequest)(nil),         // 8: kore.LSPDefinitionRequest
	(*LSPDefinitionResponse)(nil),        // 9: kore.LSPDefinitionResponse
	(*Location)(nil),                     // 10: kore.Location
	(*Range)(nil),                        // 11: kore.Range
	(*Position)(nil),                     // 12: kore.Position
	(*LSPHoverRequest)(nil),              // 13: kore.LSPHoverRequest
	(*LSPHoverResponse)(nil),             // 14: kore.LSPHoverResponse
	(*LSPReferencesRequest)(nil),         // 15: kore.LSPReferencesRequest
	(*LSPReferencesResponse)(nil),        // 16: kore.LSPReferencesResponse
	(*LSPRenameRequest)(nil),             // 17: kore.LSPRenameRequest
	(*LSPRenameResponse)(nil),            // 18: kore.LSPRenameResponse
	(*WorkspaceEdit)(nil),                // 19: kore.WorkspaceEdit
	(*DocumentChange)(nil),               // 20: kore.DocumentChange
	(*TextEdit)(nil),                     // 21: kore.TextEdit
	(*LSPDiagnosticsRequest)(nil),        // 22: kore.LSPDiagnosticsRequest
	(*LSPDiagnosticEvent)(nil),           // 23: kore.LSPDiagnosticEvent
	(*Diagnostic)(nil),                   // 24: kore.Diagnostic
	(*DiagnosticRelatedInformation)(nil), // 25: kore.DiagnosticRelatedInformation
	(*CreateSessionRequest)(nil),         // 26: kore.CreateSessionRequest
	(*GetSessionRequest)(nil),            // 27: kore.GetSessionRequest
	(*ListSessionsRequest)(nil),          // 28: kore.ListSessionsRequest
	(*ListSessionsResponse)(nil),         // 29: kore.ListSessionsResponse
	(*CloseSessionRequest)(nil),          // 30: kore.CloseSessionRequest
	(*CloseSessionResponse)(nil),         // 31: kore.CloseSessionResponse
	(*Session)(nil),                      // 32: kore.Session
	(*CreateVirtualDocRequest)(nil),      // 33: kore.CreateVirtualDocRequest
	(*CreateVirtualDocResponse)(nil),     // 34: kore.CreateVirtualDocResponse
	(*UpdateVirtualDocRequest)(nil),      // 35: kore.UpdateVirtualDocRequest
	(*UpdateVirtualDocResponse)(nil),     // 36: kore.UpdateVirtualDocResponse
	(*CloseVirtualDocRequest)(nil),       // 37: kore.CloseVirtualDocRequest
	(*CloseVirtualDocResponse)(nil),      // 38: kore.CloseVirtualDocResponse
	(*SubscribeRequest)(nil),             // 39: kore.SubscribeRequest
	(*Event)(nil),                        // 40: kore.Event
	nil,                                  // 41: kore.MessageRequest.MetadataEntry
	nil,                                  // 42: kore.MessageResponse.MetadataEntry
	nil,                                  // 43: kore.CommandRequest.EnvEntry
	nil,                                  // 44: kore.CompletionItem.DataEntry
	nil,                                  // 45: kore.CreateSessionRequest.ConfigEntry
	nil,                                  // 46: kore.Session.MetadataEntry
}
var file_api_proto_kore_proto_depIdxs = []int32{
	41, // 0: kore.MessageRequest.metadata:type_name -> kore.MessageRequest.MetadataEntry
	42, // 1: kore.MessageResponse.metadata:type_name -> kore.MessageResponse.MetadataEntry
	43, // 2: kore.CommandRequest.env:type_name -> kore.CommandRequest.EnvEntry
	0,  // 3: kore.CommandOutput.type:type_name -> kore.CommandOutput.OutputType
	7,  // 4: kore.LSPCompleteResponse.items:type_name -> kore.CompletionItem
	44, // 5: kore.CompletionItem.data:type_name -> kore.CompletionItem.DataEntry
	10, // 6: kore.LSPDefinitionResponse.locations:type_name -> kore.Location
	11, // 7: kore.Location.range:type_name -> kore.Range
	12, // 8: kore.Range.start:type_name -> kore.Position
	12, // 9: kore.Range.end:type_name -> kore.Position
	11, // 10: kore.LSPHoverResponse.range:type_name -> kore.Range
	10, // 11: kore.LSPReferencesResponse.locations:type_name -> kore.Location
	19, // 12: kore.LSPRenameResponse.edit:type_name -> kore.WorkspaceEdit
	20, // 13: kore.WorkspaceEdit.changes:type_name -> kore.DocumentChange
	21, // 14: kore.DocumentChange.edits:type_name -> kore.TextEdit
	11, // 15: kore.TextEdit.range:type_name -> kore.Range
	24, // 16: kore.LSPDiagnosticEvent.diagnostic:type_name -> kore.Diagnostic
	11, // 17: kore.Diagnostic.range:type_name -> kore.Range
	25, // 18: kore.Diagnostic.related_information:type_name -> kore.DiagnosticRelatedInformation
	10, // 19: kore.DiagnosticRelatedInformation.location:type_name -> kore.Location
	45, // 20: kore.CreateSessionRequest.config:type_name -> kore.CreateSessionRequest.ConfigEntry
	32, // 21: kore.ListSessionsResponse.sessions:type_name -> kore.Session
	46, // 22: kore.Session.metadata:type_name -> kore.Session.MetadataEntry
	26, // 23: kore.Kore.CreateSession:input_type -> kore.CreateSessionRequest
	27, // 24: kore.Kore.GetSession:input_type -> kore.GetSessionRequest
	28, // 25: kore.Kore.ListSessions:input_type -> kore.ListSessionsRequest
	30, // 26: kore.Kore.CloseSession:input_type -> kore.CloseSessionRequest
	1,  // 27: kore.Kore.SendMessage:input_type -> kore.MessageRequest
	3,  // 28: kore.Kore.ExecuteCommand:input_type -> kore.CommandRequest
	5,  // 29: kore.Kore.LSPComplete:input_type -> kore.LSPCompleteRequest
	8,  // 30: kore.Kore.LSPDefinition:input_type -> kore.LSPDefinitionRequest
	13, // 31: kore.Kore.LSPHover:input_type -> kore.LSPHoverRequest
	15, // 32: kore.Kore.LSPReferences:input_type -> kore.LSPReferencesRequest
	17, // 33: kore.Kore.LSPRename:input_type -> kore.LSPRenameRequest
	22, // 34: kore.Kore.LSPDiagnostics:input_type -> kore.LSPDiagnosticsRequest
	39, // 35: kore.Kore.SubscribeEvents:input_type -> kore.SubscribeRequest
	33, // 36: kore.Kore.CreateVirtualDocument:input_type -> kore.CreateVirtualDocRequest
	35, // 37: kore.Kore.UpdateVirtualDocument:input_type -> kore.UpdateVirtualDocRequest
	37, // 38: kore.Kore.CloseVirtualDocument:input_type -> kore.CloseVirtualDocRequest
	32, // 39: kore.Kore.CreateSession:output_type -> kore.Session
	32, // 40: kore.Kore.GetSession:output_type -> kore.Session
	29, // 41: kore.Kore.ListSessions:output_type -> kore.ListSessionsResponse
	31, // 42: kore.Kore.CloseSession:output_type -> kore.CloseSessionResponse
	2,  // 43: kore.Kore.SendMessage:output_type -> kore.MessageResponse
	4,  // 44: kore.Kore.ExecuteCommand:output_type -> kore.CommandOutput
	6,  // 45: kore.Kore.LSPComplete:output_type -> kore.LSPCompleteResponse
	9,  // 46: kore.Kore.LSPDefinition:output_type -> kore.LSPDefinitionResponse
	14, // 47: kore.Kore.LSPHover:output_type -> kore.LSPHoverResponse
	16, // 48: kore.Kore.LSPReferences:output_type -> kore.LSPReferencesResponse
	18, // 49: kore.Kore.LSPRename:output_type -> kore.LSPRenameResponse
	23, // 50: kore.Kore.LSPDiagnostics:output_type -> kore.LSPDiagnosticEvent
	40, // 51: kore.Kore.SubscribeEvents:output_type -> kore.Event
	34, // 52: kore.Kore.CreateVirtualDocument:output_type -> kore.CreateVirtualDocResponse
	36, // 53: kore.Kore.UpdateVirtualDocument:output_type -> kore.UpdateVirtualDocResponse
	38, // 54: kore.Kore.CloseVirtualDocument:output_type -> kore.CloseVirtualDocResponse
	39, // [39:55] is the sub-list for method output_type
	23, // [23:39] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_api_proto_kore_proto_init() }
func file_api_proto_kore_proto_init() {
	if File_api_proto_kore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_kore_proto_rawDesc), len(file_api_proto_kore_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_kore_proto_goTypes,
		DependencyIndexes: file_api_proto_kore_proto_depIdxs,
		EnumInfos:         file_api_proto_kore_proto_enumTypes,
		MessageInfos:      file_api_proto_kore_proto_msgTypes,
	}.Build()
	File_api_proto_kore_proto = out.File
	file_api_proto_kore_proto_goTypes = nil
	file_api_proto_kore_proto_depIdxs = nil
}
